services:
  - type: web
    name: ibl_project
    plan: free
    env: node
    buildCommand: >-
      cd backend && npm install && 
      cd ../frontend && npm install --include=dev && npm run build && 
      rm -rf ../backend/dist && cp -r dist ../backend/dist
    startCommand: >-
      cd backend && 
      echo "==== Running database migrations ==== " && 
      node scripts/migrate.js && 
      echo "==== Starting server ==== " && 
      node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: AUTO_MIGRATE
        value: "1"
      - key: DATABASE_URL
        fromDatabase:
          name: ysc_stdominic
          property: connectionString
      - key: JWT_SECRET
        value: change-me-in-render-dashboard
      # Add other environment variables from your .env file

databases:
  - name: ysc_stdominic
    databaseName: ysc_stdominic_phw5
    user: ysc_stdominic_phw5_user
    plan: free